//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParquetViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParquetViewer.Support.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected data is too large. Please select less cells..
        /// </summary>
        public static string CopyAsWhereTooLargeErrorMessage {
            get {
                return ResourceManager.GetString("CopyAsWhereTooLargeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard failed.
        /// </summary>
        public static string CopyAsWhereTooLargeErrorTitle {
            get {
                return ResourceManager.GetString("CopyAsWhereTooLargeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (CTRL+C to copy).
        /// </summary>
        public static string CopyErrorMessageText {
            get {
                return ResourceManager.GetString("CopyErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy metadata to your clipboard. Save to a file instead?.
        /// </summary>
        public static string CopyRawMetadataFailedErrorMessage {
            get {
                return ResourceManager.GetString("CopyRawMetadataFailedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy error.
        /// </summary>
        public static string CopyRawMetadataFailedErrorTitle {
            get {
                return ResourceManager.GetString("CopyRawMetadataFailedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard failed.
        /// </summary>
        public static string CopyToClipboardErrorTitle {
            get {
                return ResourceManager.GetString("CopyToClipboardErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field `{0}` with type DECIMAL({1}, {2}) contains values outside ParquetViewer&apos;s supported range between DECIMAL({3}, {4}) and DECIMAL({3}, 0).
        /// </summary>
        public static string DecimalValueTooLargeErrorMessageFormat {
            get {
                return ResourceManager.GetString("DecimalValueTooLargeErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal value too large.
        /// </summary>
        public static string DecimalValueTooLargeErrorTitle {
            get {
                return ResourceManager.GetString("DecimalValueTooLargeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered DECIMAL data outside ParquetViewer&apos;s supported range between DECIMAL({3}, {4}) and DECIMAL({3}, 0).
        /// </summary>
        public static string DecimalValueUnknownSizeTooLargeErrorMessageFormat {
            get {
                return ResourceManager.GetString("DecimalValueUnknownSizeTooLargeErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File export failed.
        /// </summary>
        public static string ExportFailedErrorTitle {
            get {
                return ResourceManager.GetString("ExportFailedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while generating the field list..
        /// </summary>
        public static string FieldListGenerationError {
            get {
                return ResourceManager.GetString("FieldListGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong (Error code: {0}). Try running ParquetViewer as administrator and try again. .
        /// </summary>
        public static string FileAssociationFailedErrorMessageFormat {
            get {
                return ResourceManager.GetString("FileAssociationFailedErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File association failed.
        /// </summary>
        public static string FileAssociationFailedErrorTitle {
            get {
                return ResourceManager.GetString("FileAssociationFailedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format. Please refer to the documentation for valid date format specifiers..
        /// </summary>
        public static string InvalidDateFormatErrorMessage {
            get {
                return ResourceManager.GetString("InvalidDateFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date Format.
        /// </summary>
        public static string InvalidDateFormatErrorTitle {
            get {
                return ResourceManager.GetString("InvalidDateFormatErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query doesn&apos;t seem to be valid. Please try again..
        /// </summary>
        public static string InvalidQueryErrorMessage {
            get {
                return ResourceManager.GetString("InvalidQueryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Query.
        /// </summary>
        public static string InvalidQueryErrorTitle {
            get {
                return ResourceManager.GetString("InvalidQueryErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists with null values are not supported. Relevant rows have been removed..
        /// </summary>
        public static string ListsWithNullsErrorMessage {
            get {
                return ResourceManager.GetString("ListsWithNullsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read all records.
        /// </summary>
        public static string ListsWithNullsErrorTitle {
            get {
                return ResourceManager.GetString("ListsWithNullsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///If you think the file is valid please consider opening an issue in the GitHub repo. See: Help → About.
        /// </summary>
        public static string MalformedFieldErrorMessageFormat {
            get {
                return ResourceManager.GetString("MalformedFieldErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while reading the file&apos;s metadata..
        /// </summary>
        public static string MetadataReadErrorMessage {
            get {
                return ResourceManager.GetString("MetadataReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Error.
        /// </summary>
        public static string MetadataReadErrorTitle {
            get {
                return ResourceManager.GetString("MetadataReadErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEMA-{0} FIELDS (TOP 5):.
        /// </summary>
        public static string MultipleSchemasDetectedEntriesErrorMessageFormat {
            get {
                return ResourceManager.GetString("MultipleSchemasDetectedEntriesErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple schemas detected..
        /// </summary>
        public static string MultipleSchemasDetectedErrorMessage {
            get {
                return ResourceManager.GetString("MultipleSchemasDetectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}s are currently unsupported.
        /// </summary>
        public static string NestedListOfTypeNotSupportedMessageFormat {
            get {
                return ResourceManager.GetString("NestedListOfTypeNotSupportedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file/folder doesn&apos;t have any fields..
        /// </summary>
        public static string NoFieldsFoundErrorMessage {
            get {
                return ResourceManager.GetString("NoFieldsFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fields found.
        /// </summary>
        public static string NoFieldsFoundErrorTitle {
            get {
                return ResourceManager.GetString("NoFieldsFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Thrift metadata available.
        /// </summary>
        public static string NoThriftMetadataAvailableErrorMessage {
            get {
                return ResourceManager.GetString("NoThriftMetadataAvailableErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid parquet files found in folder. Invalid parquet files:.
        /// </summary>
        public static string NoValidParquetFilesFoundErrorMessage {
            get {
                return ResourceManager.GetString("NoValidParquetFilesFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file/folder no longer exists: {0}Please try opening a new file or folder..
        /// </summary>
        public static string OpenFileNoLongerExistsErrorMessageFormat {
            get {
                return ResourceManager.GetString("OpenFileNoLongerExistsErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read parquet schema..
        /// </summary>
        public static string ParquetSchemaReadErrorMessage {
            get {
                return ResourceManager.GetString("ParquetSchemaReadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing query.
        /// </summary>
        public static string QueryExecutionErrorTitle {
            get {
                return ResourceManager.GetString("QueryExecutionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rendering results.
        /// </summary>
        public static string RenderResultsErrorTitle {
            get {
                return ResourceManager.GetString("RenderResultsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one field.
        /// </summary>
        public static string SelectAtLeastOneFieldErrorMessage {
            get {
                return ResourceManager.GetString("SelectAtLeastOneFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string SelectAtLeastOneFieldErrorTitle {
            get {
                return ResourceManager.GetString("SelectAtLeastOneFieldErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files could not be loaded. Invalid Parquet files:.
        /// </summary>
        public static string SomeInvalidParquetFilesFoundErrorMessage {
            get {
                return ResourceManager.GetString("SomeInvalidParquetFilesFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct `{0}` contains unsupported field: `{1}`.
        /// </summary>
        public static string StructWithUnsupportedFieldErrorMessageFormat {
            get {
                return ResourceManager.GetString("StructWithUnsupportedFieldErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many columns.
        /// </summary>
        public static string TooManyColumnsErrorTitle {
            get {
                return ResourceManager.GetString("TooManyColumnsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .xls file format supports a maximum of {0} columns.
        ///
        ///Please try another file format or reduce the amount of columns you are exporting. Your columns: {1}.
        /// </summary>
        public static string TooManyColumnsXlsErrorMessageFormat {
            get {
                return ResourceManager.GetString("TooManyColumnsXlsErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .xlsx file format supports a maximum of {0} columns.
        ///
        ///Please try another file format or reduce the amount of columns you are exporting. Your columns: {1}.
        /// </summary>
        public static string TooManyColumnsXlsxErrorMessageFormat {
            get {
                return ResourceManager.GetString("TooManyColumnsXlsxErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected assembly version was encountered: {0}.
        /// </summary>
        public static string UnexpectedAssemblyVersionErrorFormat {
            get {
                return ResourceManager.GetString("UnexpectedAssemblyVersionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load parquet file.
        ///
        ///If the problem persists please consider opening a bug ticket in the project repo: Help → About
        ///
        ///{0}.
        /// </summary>
        public static string UnexpectedFileReadErrorMessageFormat {
            get {
                return ResourceManager.GetString("UnexpectedFileReadErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown field type.
        /// </summary>
        public static string UnknownFieldTypeErrorMessage {
            get {
                return ResourceManager.GetString("UnknownFieldTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported export type: &apos;{0}&apos;.
        /// </summary>
        public static string UnsupportedExportTypeFormat {
            get {
                return ResourceManager.GetString("UnsupportedExportTypeFormat", resourceCulture);
            }
        }
    }
}
